name: Build and test project
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Check with Lint
        run: |
          npm run lint
          echo "lint..."
      - name: Run tests
        run: |
          npm run test
          echo "test..."
      - name: Build
        run: |
          npm run build
          echo "build..."
